### ISSUE TITLE
print does not include POI icon

### ISSUE THREAD

**Issue by iosefa** [gtt-project/redmine_gtt_print#8]
**Problem**
The POI icon (marker) of an issue is not included in the printed map.

**To Reproduce**
Print an issue.

**Expectation**
The map should include the POI icon (marker)

**Screenshots**
The issue has a marker:

<img width="1583" alt="Screen Shot 2021-03-11 at 16 52 13" src="https://user-images.githubusercontent.com/24607032/110754068-b80eaf80-828a-11eb-9fea-a7bf34ead528.png">

However, the printed issue does not:

<img width="809" alt="Screen Shot 2021-03-11 at 16 52 36" src="https://user-images.githubusercontent.com/24607032/110754135-cc52ac80-828a-11eb-87a3-7a8987ca5867.png">

**Platform/smartphone:**
 - Device: Macbook Pro 2019
 - OS: 11.1 (Big Sur)

**Comment by sanak** [comment]
@iosefa Okay, I will fix that. Thanks for your report.

**Comment by sanak** [comment]
@iosefa, @dkastl  
Well, this issue's cause seems to be in `redmine_gtt` side, because:
1. Docker mapfish-print container log reports the following null pointer error.
```
mapfish-print_1  | 17-Mar-2021 13:11:32.094 SEVERE [ForkJoinPool-1-worker-145] org.geotools.renderer.lite.StreamingRenderer.fireErrorEvent null
mapfish-print_1  | 	java.lang.NullPointerException
mapfish-print_1  | 		at org.geotools.renderer.lite.StreamingRenderer.getDeclaredSRS(StreamingRenderer.java:2498)
mapfish-print_1  | 		at org.geotools.renderer.lite.StreamingRenderer.reprojectSpatialFilters(StreamingRenderer.java:2487)
mapfish-print_1  | 		at org.geotools.renderer.lite.StreamingRenderer.createLiteFeatureTypeStyles(StreamingRenderer.java:2041)
mapfish-print_1  | 		at org.geotools.renderer.lite.StreamingRenderer.processStylers(StreamingRenderer.java:2214)
mapfish-print_1  | 		at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:900)
mapfish-print_1  | 		at org.geotools.renderer.lite.StreamingRenderer.paint(StreamingRenderer.java:623)
mapfish-print_1  | 		at org.mapfish.print.map.geotools.AbstractGeotoolsLayer.render(AbstractGeotoolsLayer.java:128)
mapfish-print_1  | 		at org.mapfish.print.processor.map.CreateMapProcessor.createLayerGraphics(CreateMapProcessor.java:448)
mapfish-print_1  | 		at org.mapfish.print.processor.map.CreateMapProcessor.execute(CreateMapProcessor.java:239)
mapfish-print_1  | 		at org.mapfish.print.processor.map.CreateMapProcessor.execute(CreateMapProcessor.java:100)
mapfish-print_1  | 		at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.lambda$compute$0(ProcessorGraphNode.java:203)
mapfish-print_1  | 		at org.mapfish.print.processor.AbstractProcessor$Context.mdcContext(AbstractProcessor.java:240)
mapfish-print_1  | 		at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:188)
mapfish-print_1  | 		at org.mapfish.print.processor.ProcessorDependencyGraph.tryExecuteNodes(ProcessorDependencyGraph.java:58)
mapfish-print_1  | 		at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.lambda$compute$0(ProcessorGraphNode.java:225)
mapfish-print_1  | 		at org.mapfish.print.processor.AbstractProcessor$Context.mdcContext(AbstractProcessor.java:240)
mapfish-print_1  | 		at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:188)
mapfish-print_1  | 		at org.mapfish.print.processor.ProcessorGraphNode$ProcessorNodeForkJoinTask.compute(ProcessorGraphNode.java:176)
mapfish-print_1  | 		at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
mapfish-print_1  | 		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
mapfish-print_1  | 		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
mapfish-print_1  | 		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
mapfish-print_1  | 		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
mapfish-print_1  | 		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
2. Posted JSON has the following unnecessary `crs` property in the geometry.
```
"geometry": {
    "type": "Point",
    "crs": {
        "type": "name",
        "properties": {
            "name": "EPSG:3857"
        }
    },
    "coordinates": [
        xxxxxxx,
        xxxxxxx
    ]
},
```
3. PostGIS 3 `ST_AsGeoJSON` last argument's default value seems to be changed to include `crs`.
   - PostGIS (latest): https://postgis.net/docs/ST_AsGeoJSON.html
      ```sql
      text ST_AsGeoJSON(geometry geom, integer maxdecimaldigits=9, integer options=8);
      ```
      > 8: GeoJSON Short CRS if not EPSG:4326 (default)
   - PostGIS 2.5: https://postgis.net/docs/manual-2.5/ST_AsGeoJSON.html
      ```sql
      text ST_AsGeoJSON(geometry geom, integer maxdecimaldigits=15, integer options=0);
      ```
      > 0: means no option (default value)

---

Currently, the function is inside `redmine_gtt` plugin, so I will fix `redmine_gtt` side.
- https://github.com/gtt-project/redmine_gtt/blob/main/lib/redmine_gtt/patches/geojson_attribute.rb#L66-L83
